#!/usr/bin/env bash
HASH_TYPE=md5
HASH_EXT=.hash
OVERRIDE_HASH=false
OVERRIDE_HASH_IF_AN_ERROR=true
DEBUG=false
DEBUG_OUTPUT_HASH=false
CHECKSUM_FILENAME=checksums${HASH_EXT}
ERROR_FLAG_FILENAME=error${HASH_EXT}
OK_FLAG_FILENAME=ok${HASH_EXT}
IGNORE_FILES=" -not -name ${CHECKSUM_FILENAME} -not -name ${ERROR_FLAG_FILENAME} -not -name ${OK_FLAG_FILENAME} "
FILE_PATH=${1}
if [[ -z "$FILE_PATH" ]]; then
    FILE_PATH=${PWD}/
else
    FILE_PATH=$(echo "${FILE_PATH}" | sed 's:/*$::')/
    FILE_PATH="${FILE_PATH//\/\///}"
fi
CHECKSUM_FILE_PATH="${FILE_PATH}${CHECKSUM_FILENAME}"
FILE_OK="${FILE_PATH}${OK_FLAG_FILENAME}"
FILE_ERROR="${FILE_PATH}${ERROR_FLAG_FILENAME}"